services:
  - type: web
    name: n8n-supabase
    env: node
    plan: free
    region: oregon
    healthCheckPath: /healthz
    buildCommand: "pnpm install --frozen-lockfile && pnpm run build"
    startCommand: "cd packages/cli && node bin/n8n start"
    autoDeploy: true
    envVars:
      # Supabase Database Configuration
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.caamtdhihhmvtqltgcvz.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PASSWORD
        value: pC4@mbs5Tz*9j@8
      - key: DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED
        value: false
      
      # n8n Core Configuration
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      
      # Security Keys (from your existing setup)
      - key: N8N_ENCRYPTION_KEY
        value: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      - key: N8N_USER_MANAGEMENT_JWT_SECRET
        value: 21471c0273a64acb05f7308afba96f6c4068d513c1e34a588b4245b117b01be7
      
      # Optional: Basic Authentication
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: n8n_admin_2024
      
      # Performance Settings
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 336